### ISSUE TITLE
OpenJdk 11 look like not working in the nano server

### ISSUE THREAD

**Issue by minefreeman** [jenkinsci/docker-slave#108]
Hi, 
      I‘m new to use the Jenkins, and when  I use the 

> Dockerfile-windows-nanoserver-jdk11

 to make an image. Everything is fine, but when I try to run 

`docker run -i --rm --name agent --init myagentt:1.0 java -jar C:/ProgramData/Jenkins/agent.jar`

The error happen

`C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: container 554c650a20b85fb9960f1902eec65d2ac1ac36e9cc1e639d40263da4ad463954 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF650559D2B: (caller: 00007FF65050E13A) Exception(6) tid(390) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"java -jar C:/ProgramData/Jenkins/agent.jar","User":"jenkins","WorkingDirectory":"C:\\Users\\jenkins\\Jenkins","Environment":{"AGENT_WORKDIR":"C:/Users/jenkins/Jenkins/Agent","LOCALAPPDATA":"C:\\Users\\ContainerAdministrator\\AppData\\Local","PATH":"C:\\Windows\\system32;C:\\Windows;C:\\Program Files\\PowerShell;","PSCORE":"\\PowerShell\\pwsh.exe","PSModuleAnalysisCachePath":"\\Microsoft\\Windows\\PowerShell\\docker\\ModuleAnalysisCache","ProgramFiles":"C:\\Program Files","WindowsPATH":"C:\\Windows\\system32;C:\\Windows"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.`

So I try to run this image

`docker run -i --rm --name agent --init myagentt:1.0`

then

`PS C:\Users\jenkins\Jenkins> java -jar C:/ProgramData/Jenkins/agent.jar
java -jar C:/ProgramData/Jenkins/agent.jar
java : The term 'java' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ java -jar C:/ProgramData/Jenkins/agent.jar
+ ~~~~
+ CategoryInfo          : ObjectNotFound: (java:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException`

When I try this, it still get some error:

`C:\openjdk-11.0.3-1\bin\java -jar C:/ProgramData/Jenkins/agent.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\openjdk-11.0.3-1\bin\net.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
        at java.base/java.lang.System.loadLibrary(System.java:1867)
        at java.base/sun.nio.fs.WindowsNativeDispatcher$1.run(WindowsNativeDispatcher.java:1138)
        at java.base/sun.nio.fs.WindowsNativeDispatcher$1.run(WindowsNativeDispatcher.java:1135)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.nio.fs.WindowsNativeDispatcher.<clinit>(WindowsNativeDispatcher.java:1135)
        at java.base/sun.nio.fs.WindowsFileAttributes.get(WindowsFileAttributes.java:308)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:51)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:256)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:521)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:747)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)`

but when I try to get the java version, it works.

`PS C:\Users\jenkins\Jenkins> c:/openjdk-11.0.3-1/bin/javaw -version                         
c:/openjdk-11.0.3-1/bin/javaw -version
openjdk version "11.0.3-ojdkbuild" 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3-ojdkbuild+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3-ojdkbuild+7-LTS, mixed mode)`

And

`PS C:\Users\jenkins\Jenkins> [System.Environment]::GetEnvironmentVariable('PATH','machine')      
[System.Environment]::GetEnvironmentVariable('PATH','machine')
C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;;%JAVA_HOME%\bin`

Am I missing something or there still have some operation need to do?

**Comment by minefreeman** [comment]
well, Iooks like it is a bug.
I change to openjdk-11.0.6.10-1, it's work now, but still need to use

`c:\openjdk-11.0.6-1\bin\java -jar C:/ProgramData/Jenkins/agent.jar`

And I try to make it like :

`PS C:\Users\jenkins\Jenkins> [System.Environment]::GetEnvironmentVariable('PATH','machine')
[System.Environment]::GetEnvironmentVariable('PATH','machine')
C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;C:\mingit\cmd;C:\openjdk-11.0.6-1\bin`

But no help to run that
`java -jar C:/ProgramData/Jenkins/agent.jar`

**Comment by slide** [comment]
Java 11.0.6 is the version used now. It should be in the latest nanoserver image.
